#!/bin/bash

BACKEND_HOST=${BACKEND_HOST:=0.0.0.0}
BACKEND_PORT=${BACKEND_PORT:=42000}
FRONTEND_HOST=${FRONTEND_HOST:=0.0.0.0}
FRONTEND_PORT=${FRONTEND_PORT:=42042}

flask --app=main:app run --debug --host=$FRONTEND_HOST --port=$FRONTEND_PORT